language: java
jdk: oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_6e96b4c0a9f9_key -iv $encrypted_6e96b4c0a9f9_iv
  -in application.properties.enc -out fluke-goal-rest/src/main/resources/application.properties
  -d
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: dm@sernet.de
  password:
    secure: "eWXf8eVOYWYoQxMDN0Pn2fxvCqvOwTnCuJewARlqfRI0ykFPHsWEKhCa3S6O3QSohFk4v0EBZ6Sb1yrPakGUL59q3crg1e/ge0DNHft+o/LVBs8/tYtPzCuWUibnmc2JcU5MtkZ2e85vUQKjRcPkMaF9JH9NBWv07D/LT2NUxak0ifIkF9Fdupz6m3XBo6kJpLnxNHr/Ev/A9ECh1olTs5/e4hU3TuQmzfAopmGSUGk0kbWQsZhtd6yIqAlGyTd55I81RPJh2ALdHSNJ4XiFlBCPa8JZUsBvPyQZjloI+CDWQGem3CXVbgweeWUcOzf9JtX8hpafQQq4MyDV+3OnSbsjXP0hEoysu4XAqgk3OZ6ZRjdSLmWEzUCeZEsVn3zWI8fOZEkLcV1klOv/j2amjO+QovRNbVftH3EjqbaDElQ2f7ACp88tLqhZE/aRAQe5WM0bDTFd16HGE4k8a0obJ/xf4mGNBwnT0c620OkE1YDwdlOAShKmfggw5WkFPvbboxVtCGWxwOXW8oF8iQhimKZoG0hfisYItO7/NmVUBPluw4D/4WeE1J2h5vxs0D4KEB9zesnmc62gqS1VvZF5+zkoKjT9hLue/LCXg9T5nTpOMZOEbmXgcqPAc4XOZCzP/dpEWepKmXfAfy+EOdTzBJvHj5LFGtPq1X6XZxc2U5c="
  organization: murygin
  space: development
  on:
    repo: murygin/fluke
